# Generated by Django 4.2.2 on 2023-07-03 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tea_type",
                    models.CharField(
                        choices=[
                            ("GREEN", "GREEN"),
                            ("BLACK", "BLACK"),
                            ("CREAM", "CREAM"),
                            ("OOLONG", "OOLONG"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sugar",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "cold_hot",
                    models.CharField(
                        choices=[("hot", "hot"), ("cold", "cold")], max_length=40
                    ),
                ),
                ("flavour", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
